### ISSUE TITLE
Unbiased fits for ns for large catalogues

### ISSUE THREAD

**Issue by robertdstein** [IceCubeOpenSource/flarestack#5]
**Describe the bug**
Currently ns bias plots indicate fitted parameters are not well-recovered for large (O(1-10k)) catalogues.

**To Reproduce**
1. Run e.g `flarestack/analyses/agn_cores/test_completeness.py`
2. See bias plot

**Expected behavior**
Bias-free fit.

**Comment by robertdstein** [comment]
OK, now I'm really sure that this was down to bad PDF construction for IC40. Using the official  binning and 9 sources I get:

[bias_n_s_ic40_standard_binning.pdf](https://github.com/IceCubeOpenSource/flarestack/files/4112894/bias_n_s_ic40_standard_binning.pdf)

Using a "half-half" binning (halving bin density in both sindec and logE), I get: 

[bias_n_s_halfhalf_binning.pdf](https://github.com/IceCubeOpenSource/flarestack/files/4112896/bias_n_s_halfhalf_binning.pdf)

This squares with what @fbradascio found, where MC-based PDFs do not show this problem. Likely to have impacted #15 too.

**Comment by fbradascio** [comment]
Confirmed that using ~10000 sources with the diffuse sample (8years) does not give a bias because of the MC PDF construction.
[bias_n_s.pdf](https://github.com/IceCubeOpenSource/flarestack/files/4121934/bias_n_s.pdf)

This bug is now understood: the more sources you have the more important is that your PDFs are built correctly. Low statistics PDF from data can give this effect.

**Comment by fbradascio** [comment]
When trying to create again IC40 PDFs, you might encounter the following error:
`Traceback (most recent call last):
  File "flarestack/analyses/agn_cores/test_completeness_10year_cluster.py", line 114, in <module>
    mh_dict["scale"] = 2 * mh.guess_scale()
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/minimisation.py", line 301, in guess_scale
    return 1.5 * flux_to_k(self.guess_discovery_potential())
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/minimisation.py", line 305, in guess_discovery_potential
    self.seasons, dict(self.inj_dict), self.sources, dict(self.llh_dict))
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/utils/asimov_estimator.py", line 65, in estimate_discovery_potential
    llh = LLH.create(season, sources, new_llh_dict)
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/llh.py", line 123, in create
    return cls.subclasses[llh_name](season, sources, llh_dict)
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/llh.py", line 480, in __init__
    LLH.__init__(self, season, sources, llh_dict)
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/llh.py", line 101, in __init__
    self.acceptance, self.energy_weight_f = self.create_energy_functions()
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/core/llh.py", line 520, in create_energy_functions
    self.season.log_e_bins)
  File "/afs/ifh.de/user/b/bradascf/flarestack/flarestack/utils/make_SoB_splines.py", line 192, in make_2d_spline_from_hist
    kx=order, ky=order, s=0)
  File "/afs/ifh.de/user/b/bradascf/.local/lib/python3.6/site-packages/scipy/interpolate/fitpack2.py", line 1175, in __init__
    raise ValueError('x dimension of z must have same number of '
ValueError: x dimension of z must have same number of elements as x`

It comes from IC40 PDFs built assuming a fixed spectrum that is used for the guess function. You just need to delete them. They are found in: `flarestack__data/input/input/SoB_splines/` followed by a series of random numbers. The same might happen for the acceptance function.
